# Generated by Django 4.1.6 on 2023-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.CharField(max_length=100)),
                ("output_data", models.CharField(max_length=100)),
            ],
        ),
    ]
