# Generated by Django 4.1.6 on 2023-07-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycalc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="input_data2",
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
    ]
