# Generated by Django 4.1.6 on 2023-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycalc", "0002_calculation_input_data2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculationdb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Calculation",
        ),
    ]
