# Generated by Django 4.1.6 on 2023-07-12 11:50

from django.db import migrations, models
import mycalc.models


class Migration(migrations.Migration):

    dependencies = [
        ("mycalc", "0003_calculationdb_delete_calculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationdb",
            name="input_data2",
            field=models.CharField(
                default=0,
                max_length=100,
                validators=[mycalc.models.validate_integer_only],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calculationdb",
            name="input_data",
            field=models.CharField(
                max_length=100, validators=[mycalc.models.validate_integer_only]
            ),
        ),
    ]
