# Generated by Django 4.1.6 on 2023-07-12 14:05

from django.db import migrations, models
import mycalc.models


class Migration(migrations.Migration):

    dependencies = [
        ("mycalc", "0004_calculationdb_input_data2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculationdb",
            name="input_data2",
        ),
        migrations.AlterField(
            model_name="calculationdb",
            name="input_data",
            field=models.CharField(
                default="0",
                max_length=100,
                validators=[mycalc.models.validate_integer_only],
            ),
        ),
    ]
